name: build
on:
  release:
    types: [created]
  push:
    tags:
      - 'v*'
jobs:
  build:
    name: build
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            platform: linux-x64
            target: cplus-linux-x64
          - os: ubuntu-latest
            platform: linux-arm64
            target: cplus-linux-arm64
            arch: aarch64-linux-gnu
          - os: macos-latest
            platform: macos-universal
            target: cplus-macos-universal
          - os: windows-latest
            platform: windows-x64
            target: cplus-windows-x64.exe
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - name: get-version
        id: version
        shell: bash
        run: |
          VERSION=$(jq -r .version config.json)
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          echo "tag=$VERSION" >> $GITHUB_OUTPUT
      - name: check-tag
        shell: bash
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          if gh release view ${{ env.VERSION }} --repo ${{ github.repository }} > /dev/null 2>&1 && [ "${{ github.event_name }}" == "push" ]; then
            echo "Already released"
            exit 0
          fi
      - name: install-arm-linux
        if: matrix.platform == 'linux-arm64'
        run: sudo apt-get update && sudo apt-get install -y g++-aarch64-linux-gnu
      - name: build-linux-x64
        if: matrix.platform == 'linux-x64'
        run: g++ -std=c++20 src/main.cpp src/environment/*.cpp src/lexer/*.cpp src/parser/*.cpp src/ast/*.cpp -I src/ -o ${{ env.VERSION }}-${{ matrix.target }}
      - name: build-linux-arm64
        if: matrix.platform == 'linux-arm64'
        run: aarch64-linux-gnu-g++ -std=c++20 src/main.cpp src/environment/*.cpp src/lexer/*.cpp src/parser/*.cpp src/ast/*.cpp -I src/ -o ${{ env.VERSION }}-${{ matrix.target }}
      - name: build-macos
        if: matrix.platform == 'macos-universal'
        run: |
          clang++ -std=c++20 -arch x86_64 src/main.cpp src/environment/*.cpp src/lexer/*.cpp src/parser/*.cpp src/ast/*.cpp -I src/ -o cplus-x64
          clang++ -std=c++20 -arch arm64 src/main.cpp src/environment/*.cpp src/lexer/*.cpp src/parser/*.cpp src/ast/*.cpp -I src/ -o cplus-arm64
          lipo -create -output ${{ env.VERSION }}-${{ matrix.target }} cplus-x64 cplus-arm64
      - name: build-windows
        if: matrix.platform == 'windows-x64'
        run: g++ -std=c++20 src/main.cpp src/environment/*.cpp src/lexer/*.cpp src/parser/*.cpp src/ast/*.cpp -I src/ -o ${{ env.VERSION }}-${{ matrix.target }}
      - name: upload
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/') || github.event_name == 'release'
        with:
          files: ${{ env.VERSION }}-${{ matrix.target }}
          tag_name: ${{ env.VERSION }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
